# Generated by Django 6.0.2 on 2026-04-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('publicacao', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.editora')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('livro', models.ManyToManyField(related_name='autores', to='edu.livro')),
            ],
        ),
    ]
